spring:
  datasource:
    url: jdbc:mysql://localhost:3306/form_builder
    username: root
    password: Pass@123

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  cache:
    type: redis


