spring:
  datasource:
    url: jdbc:mysql://localhost:3306/form_builder
    username: root
    password: Pass@123

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false


